### ISSUE TITLE
scipy.misc.toimage deprecated

### ISSUE THREAD

**Issue by koenvangils** [MedPhysQC/MG_Flatfield#2]
scipy.misc.toimage is deprecated. Because of this the script does not work on a fresh WAD install on Ubuntu 20.04 LTS.  Pillow’s Image.fromarray can be used in stead. See https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.toimage.html .

**Comment by asch99** [comment]
Already fixed in #5845544073fff106d7d20c0e199242fbf46786e8 and available in pre-release (as needed WAD-QC update is not yet released, but you have it).
